language: rust

env:
  - IN_CI=true

os:
  - linux
  - osx

before_install:
  - set -e
  - export RUSTFLAGS="-D warnings"
  - rustup self update
  - rustup component add rustfmt-preview clippy-preview
  - cargo clippy --version

addons:
  chrome: stable

script:
  - cargo fmt --all -- --check
  - cargo clippy --all --tests --examples
  - env RUST_BACKTRACE=1 RUST_LOG=headless_chrome=trace cargo test -- --nocapture
