language: rust

os:
  - linux
  - osx
  - windows

before_install:
  - set -e
  - export RUSTFLAGS="-D warnings"
  - rustup self update
  - rustup component add rustfmt-preview clippy-preview

script:
  - cargo fmt --all -- --check
  - cargo clippy --tests
